name: mario-rl-env
channels:
  - pytorch-nightly
  - defaults
dependencies:
  - blas=1.0
  - brotli-python=1.0.9
  - ca-certificates=2023.12.12
  - certifi=2024.2.2
  - charset-normalizer=2.0.4
  - filelock=3.13.1
  - freetype=2.12.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - idna=3.4
  - jinja2=3.1.3
  - jpeg=9e
  - lcms2=2.12
  - lerc=3.0
  - libcxx=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libjpeg-turbo=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - networkx=3.1
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openjpeg=2.3.0
  - openssl=3.0.13
  - pillow=10.2.0
  - pip=23.3.1
  - pysocks=1.7.1
  - python=3.8.18
  - pytorch=2.3.0.dev20240310
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.2.2
  - sqlite=3.41.2
  - sympy=1.12
  - tk=8.6.12
  - torchaudio=2.2.0.dev20240310
  - torchvision=0.18.0.dev20240310
  - typing_extensions=4.9.0
  - urllib3=2.1.0
  - wheel=0.41.2
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - cloudpickle==3.0.0
      - contourpy==1.1.1
      - cycler==0.12.1
      - fonttools==4.49.0
      - fsspec==2024.2.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - gym-super-mario-bros==7.4.0
      - importlib-metadata==7.0.2
      - importlib-resources==6.1.3
      - kiwisolver==1.4.5
      - matplotlib==3.7.5
      - nes-py==8.2.1
      - packaging==24.0
      - pyglet==1.5.21
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - six==1.16.0
      - tensordict==0.3.0
      - torchrl==0.3.0
      - tqdm==4.66.2
      - zipp==3.17.0
